# Generated by Django 4.0.5 on 2022-07-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angapp', '0002_alter_employees_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Department',
            field=models.CharField(max_length=100),
        ),
    ]
